version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: gro_ats_frontend
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    volumes:
      - ./ssl:/etc/nginx/ssl:ro
    networks:
      - gro_ats_network
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: gro_ats_backend
    ports:
      - "8001:8001"
    environment:
      - MONGO_URL=${MONGO_URL:-mongodb+srv://camerongmccallum:qlJuuvzApoAsqQE2@ats.jfoq9p.mongodb.net/?retryWrites=true&w=majority&appName=ATS}
      - DB_NAME=${DB_NAME:-ATS}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY:-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}
      - CAREERS_SITE_URL=${CAREERS_SITE_URL:-https://childcare-career-hub.lovable.app}
      - CAREERS_WEBHOOK_SECRET=${CAREERS_WEBHOOK_SECRET:-gro-regionalchildcare-webhook-2025}
      - SECRET_KEY=${SECRET_KEY:-ats-regionalchildcare-secure-secret-key-2025}
      - ENVIRONMENT=${ENVIRONMENT:-production}
      - DEBUG=${DEBUG:-false}
      - DOMAIN=${DOMAIN:-ats.regionalchildcare.com}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    networks:
      - gro_ats_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/api/dashboard/stats"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  gro_ats_network:
    driver: bridge